print("\n"*3)
print("*"*150)
print("                                        _ _ _ _   _ _       _   _ _ _                ")
print("                                       |  _ _ _| |   \     | | |  _  \         ")
print("                                       | |       | |\ \    | | | |  \ \           ")
print("                                       | |_ _    | | \ \   | | | |   | |              ")
print("                                       |  _ _|   | |  \ \  | | | |   | |            ")
print("                                       | |       | |   \ \ | | | |   | |         ")
print("                                       | |_ _ _  | |    \ \| | | |_ / /              ")
print("                                       |_ _ _ _| |_|     \_ _| |_ _ _/                   ")
print("*"*150)
x=input("Press any key to Exit the Program: ")
